# Permalinks
#
# Use of `relative_permalinks` ensures post links from the index work properly.
permalink:           pretty

# Setup
title:               My Weblog
tagline:             
description:         'Get in touch at <a href="https://twitter.com/avidiotic" target="_blank">@avidiotic</a>.'
url:                 http://www.aviagarwal.net
baseurl:             ''
paginate:            5

# About/contact
author:
  name:              Avi Agarwal
  url:               https://twitter.com/avidiotic
