# Permalinks
#
# Use of `relative_permalinks` ensures post links from the index work properly.
permalink:           pretty

# Setup
title:               Untitled
tagline:             'This is my brain dump'
description:         'Maintained, written and edited by <a href="https://twitter.com/avidiotic" target="_blank">@avidiotic</a>.'
url:                 http://lanyon.getpoole.com
baseurl:             ''
paginate:            5

# About/contact
author:
  name:              Avi Agarwal
  url:               https://twitter.com/avidiotic
